language: node_js
node_js:
  - "stable"
install:
  - npm install
addons:
  postgresql: "9.4"
env:
  global:
    - SECRET=15cacf1692e34e33bedddb59a974a5263f8f4861c5a294b1373093ec4ef4e50a
before_script:
  - psql -c 'create database banka;' -U postgres
  - chmod 0777 ./node_modules/.bin/mocha
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm test
cache:
  directories:
    - "node_modules"
after_success:
  - npm run coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
notifications:
  email: false